version: '3'

services:
  nginx-websocket-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${LISTEN_PORT1}:${LISTEN_PORT1}"
      - "${LISTEN_PORT2}:${LISTEN_PORT2}"
    env_file:
      - .env
