version: '3'

services:
  nginx-websocket-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LISTEN_PORT1
        - WS_BACKEND1
        - LISTEN_PORT2
        - WS_BACKEND2
    ports:
      - "${LISTEN_PORT1}:${LISTEN_PORT1}"
      - "${LISTEN_PORT2}:${LISTEN_PORT2}"
    env_file:
      - .env
